name: copularr
description: iOS Usenet Manager
version: 1.1.0+44

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  bottom_navy_bar: ^5.3.2
  cupertino_icons: ^0.1.3
  encrypt: ^4.0.0
  file_picker: ^1.4.3+2
  flutter:
    sdk: flutter
  flutter_advanced_networkimage: ^0.6.3
  flutter_redux: ^0.6.0
  flutter_sticky_header: ^0.4.0
  f_logs: ^1.2.2
  http: ^0.12.0+4
  intl: ^0.16.1
  package_info: ^0.4.0+13
  path_provider: ^1.5.1
  percent_indicator: ^2.1.1+1
  permission_handler: ^4.2.0+hotfix.2
  redux: ^4.0.0
  shared_preferences: ^0.5.6+1
  stack_trace: ^1.9.3
  table_calendar: ^2.2.2
  url_launcher: ^5.4.1
  validators: ^2.0.0+1

dev_dependencies:
  dapackages: ^1.1.1
  flutter_launcher_icons: ^0.7.4
  flutter_native_splash: ^0.1.9
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/accent_color.png
    - assets/images/secondary_color.png
    - assets/images/noalbumart.png
    - assets/images/services/imdb.png
    - assets/images/services/youtube.png
    - assets/images/services/tvmaze.png
    - assets/images/services/thetvdb.png
    - assets/images/services/themoviedb.png
    - assets/images/services/discogs.png
    - assets/images/services/bandsintown.png
    - assets/images/services/lastfm.png
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  image: "assets/icon/icon.png"
  color: "#32323E"
  android: true
